# Generated by Django 2.0.3 on 2018-03-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quikly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cycle', to='quikly.QuiklyUser'),
        ),
    ]
